### GET all Employees
GET http://localhost:4004/odata/v4/employeeService/Employees

### get division
GET http://localhost:4004/odata/v4/employeeService/Divisions

### get departments
GET http://localhost:4004/odata/v4/employeeService/Departments


### POST Department
POST http://localhost:4004/odata/v4/employeeService/Departments
Content-Type: application/json

{
  "name": "Developer",
  "division_ID": "11111111-1111-1111-1111-111111111111"
}

### POST employee
POST http://localhost:4004/odata/v4/employeeService/Employees
Content-Type: application/json

{
  "name": "rahul",
  "email": "rahul123@gmail.com",
  "phone":"2222222222",
  "department_ID":"3bc717de-c2c5-40d2-bc9a-e442f249792c",
  "division_ID": "11111111-1111-1111-1111-111111111111"
}


### delete department
DELETE http://localhost:4004/odata/v4/employeeService/Departments('3bc717de-c2c5-40d2-bc9a-e442f249792c')